common:
  app:
    url: "%env(APP_URL)%"
    name: "%env(APP_NAME)%"
    version: "%version%"
    logo: "%env(APP_LOGO)%"
    project_url: https://github.com/SchulIT/servicecenter
  locales: "%locales%"
  menu: mainMenu