#index:
#    path: /
#    controller: App\Controller\DefaultController::index

lightsaml_sp:
    resource: "@LightSamlSpBundle/Resources/config/routing.yml"
    prefix: saml

common:
    resource: "@CommonBundle/Controller"
    type: annotation

exchange:
    resource: "@IdpExchangeBundle/Controller"
    type: annotation
    prefix: /admin/exchange
    
composer:
    resource: "@ComposerDependencyListBundle/Controller"
    type: annotation
    prefix: /dependencies

logout:
    path: /logout